version: "3.8"
services:
  app:
    image: "sergiodevops/api-app:latest"
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env.production
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
